timeout: 0
verbose: yes

/Rawline
protocol: limine
path: boot():/boot/loader.elf
module_path: boot():/boot/kernel.rwl
module_path: boot():/boot/miraboot.rwl
module_path: boot():/boot/memory.rwl
module_path: boot():/boot/compositor.rwl
module_path: boot():/boot/taskbar.rwl
module_path: boot():/boot/input.rwl
module_path: boot():/boot/storage.rwl
module_path: boot():/boot/filesystem.rwl
